BASIC = "Basic"
UNPAIRED = "Unpaired"
CRITICAL = "Critical"
EXTREME = "Extreme"
IMPOSSIBLE = "Impossible"
WHATAHERO = "What A Hero"
SUCCESSTYPES = [BASIC, CRITICAL, EXTREME, IMPOSSIBLE]
JOINER = ", "
DIESIZE = 6
HEADS = "heads"
TAILS = "tails"
COIN = [HEADS, TAILS]
REROLL = "Reroll"
RISKROLL = "Risk Roll"
ALL_OR_NOTHING = "All-or-Nothing Roll"
REGULAR_ROLL = "Regular Roll"